# Generated by Django 2.0.2 on 2018-04-03 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processlib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ask_for_token', models.BooleanField()),
                ('require_token', models.BooleanField()),
                ('available_articles', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processlib.Process')),
                ('token', models.CharField(default='', max_length=255)),
                ('organization_id', models.CharField(default='', max_length=255)),
                ('person_id', models.CharField(default='', max_length=255)),
                ('recipient', models.TextField()),
                ('articles', models.TextField()),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.OrderConfig')),
            ],
            bases=('processlib.process',),
        ),
    ]
