# Generated by Django 2.0.2 on 2018-04-03 11:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityInstance',
            fields=[
                ('status', models.CharField(default='instantiated', max_length=16)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('activity_name', models.CharField(max_length=255)),
                ('instantiated_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
                ('predecessors', models.ManyToManyField(related_name='successors', to='processlib.ActivityInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('flow_label', models.CharField(max_length=255)),
                ('started_at', models.DateTimeField(null=True)),
                ('finished_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='activityinstance',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_activity_instances', to='processlib.Process'),
        ),
    ]
