# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-12 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processlib', '0004_auto_20180412_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
