# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-16 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processlib', '0005_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityinstance',
            name='scheduled_at',
            field=models.DateTimeField(null=True),
        ),
    ]
