# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-17 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processlib', '0006_activityinstance_scheduled_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(default='started', max_length=16),
        ),
    ]
