# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-20 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processlib', '0007_auto_20180417_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityinstance',
            name='status',
            field=models.CharField(choices=[('instantiated', 'instantiated'), ('scheduled', 'scheduled'), ('started', 'started'), ('canceled', 'canceled'), ('finished', 'finished'), ('error', 'error')], default='instantiated', max_length=16),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('canceled', 'canceled'), ('finished', 'finished')], default='started', max_length=16),
        ),
    ]
