# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-25 11:09
from __future__ import unicode_literals

from django.db import migrations


def rename_finished_done(apps, schema_editor):
    Process = apps.get_model('processlib', 'Process')
    ActivityInstance = apps.get_model('processlib', 'ActivityInstance')

    Process.objects.filter(status='finished').update(status='done')
    ActivityInstance.objects.filter(status='finished').update(status='done')


def rename_done_finished(apps, schema_editor):
    Process = apps.get_model('processlib', 'Process')
    ActivityInstance = apps.get_model('processlib', 'ActivityInstance')

    Process.objects.filter(status='done').update(status='finished')
    ActivityInstance.objects.filter(status='done').update(status='finished')


class Migration(migrations.Migration):

    dependencies = [
        ('processlib', '0008_auto_20180420_1023'),
    ]

    operations = [
        migrations.RunPython(rename_finished_done, rename_done_finished)
    ]
