# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-27 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processlib', '0009_auto_20180425_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='process',
            options={'ordering': ('-finished_at', '-started_at'), 'verbose_name': 'Process'},
        ),
        migrations.AddField(
            model_name='activityinstance',
            name='modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activityinstance',
            name='status',
            field=models.CharField(choices=[('instantiated', 'instantiated'), ('scheduled', 'scheduled'), ('started', 'started'), ('canceled', 'canceled'), ('done', 'done'), ('error', 'error')], default='instantiated', max_length=16),
        ),
        migrations.AlterField(
            model_name='process',
            name='status',
            field=models.CharField(choices=[('started', 'started'), ('canceled', 'canceled'), ('done', 'done')], default='started', max_length=16),
        ),
    ]
