# Generated by Django 2.0.2 on 2018-04-03 11:22

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processlib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignParticipationProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processlib.Process')),
                ('target_campaign_id', models.CharField(default='', max_length=255)),
                ('target_step_id', models.CharField(default='', max_length=255)),
                ('event_title', models.CharField(default='', max_length=255)),
                ('event_text', models.CharField(default='', max_length=255)),
                ('event_id', models.CharField(default='', max_length=255)),
            ],
            bases=('processlib.process',),
        ),
        migrations.CreateModel(
            name='EinfachpackenOrderProcess',
            fields=[
                ('process_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='processlib.Process')),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('erp_order_id', models.CharField(blank=True, default='', max_length=255)),
            ],
            bases=('processlib.process',),
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='einfachpackenorderprocess',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_inbox.Organisation'),
        ),
        migrations.AddField(
            model_name='einfachpackenorderprocess',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_inbox.Person'),
        ),
        migrations.AddField(
            model_name='campaignparticipationprocess',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_inbox.Organisation'),
        ),
        migrations.AddField(
            model_name='campaignparticipationprocess',
            name='person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_inbox.Person'),
        ),
    ]
